"""Provider contract: given a scratch directory and a prompt, produce markdown."""

import logging
from abc import ABC, abstractmethod
from pathlib import Path

from ..models import FailureKind, ProviderError
from ..prompts import MANUSCRIPT_FILE, OUTPUT_FILE, REVIEW_FILE
from .failures import classify

log = logging.getLogger(__name__)


class CliProvider(ABC):
    """Runs a model over files in a scratch directory.

    The scratch directory is the only thing a provider ever sees. Client folders
    are never passed to a model, so no model can damage the user's papers.
    """

    name = "provider"
    model_label = "provider"
    # Set by the caller after each call; None when the tool reported nothing.
    last_usage = None
    # Raw output of the most recent call. Codex prints its token summary here
    # and writes no session log in `exec` mode, so this is the only source.
    last_stdout = ""

    @abstractmethod
    def _invoke(self, workdir: Path, prompt: str) -> str:
        """Run the underlying tool. Returns stdout, which is used only for diagnostics."""

    def preflight(self) -> None:
        """Fail fast if the tool is unusable, before any client is processed."""

    def generate(self, workdir: Path, prompt: str) -> str:
        stdout = self._invoke(workdir, prompt)
        self.last_stdout = stdout
        output = workdir / OUTPUT_FILE
        if not output.exists():
            # Nothing was produced, so the text is diagnostic rather than content.
            # A usage limit or an expired login must stop the whole phase, since
            # every remaining client would hit it too; anything else is just an
            # empty result for this one paper.
            kind = classify(stdout)
            if kind not in (FailureKind.USAGE_LIMIT, FailureKind.AUTH_REQUIRED):
                kind = FailureKind.EMPTY_OUTPUT
            raise ProviderError(
                kind,
                f"{self.name} did not create {OUTPUT_FILE}. Last output: {stdout[-500:]!r}",
            )
        text = output.read_text(encoding="utf-8", errors="replace")
        if not text.strip():
            raise ProviderError(
                FailureKind.EMPTY_OUTPUT, f"{self.name} wrote an empty {OUTPUT_FILE}."
            )
        return text


class MockProvider(CliProvider):
    """Deterministic stand-in used by test mode and the test suite.

    Echoes the input back with a plausible structure so the surrounding pipeline —
    naming, idempotency, validation, reporting — can be exercised end to end
    without a login or any usage cost.
    """

    name = "mock"
    model_label = "mock"

    def _invoke(self, workdir: Path, prompt: str) -> str:
        manuscript = workdir / MANUSCRIPT_FILE
        source = (
            manuscript.read_text(encoding="utf-8", errors="replace")
            if manuscript.exists()
            else ""
        )
        is_revision = (workdir / REVIEW_FILE).exists()

        if is_revision:
            body = source.rstrip() + (
                "\n\n## Revision Notes\n\n"
                "Generated by the mock provider; the manuscript is reproduced unchanged.\n"
            )
        else:
            body = (
                "# RESEARCH PAPER REVIEW REPORT\n\n"
                "**Overall Recommendation:** Major Revision\n\n"
                "## 1. Executive Summary\n\n"
                "Mock review generated without a model. Not a real assessment.\n\n"
                "## 2. Overall Assessment\n\n"
                f"The manuscript supplied was {len(source)} characters long.\n\n"
                "## 13. Final Reviewer Recommendation\n\n"
                "Major Revision (mock).\n"
            )

        (workdir / OUTPUT_FILE).write_text(body, encoding="utf-8")
        return "mock provider completed"
